---
- name: Install Flyway
  hosts: all
  tasks:
    - name: setup Ruby
      import_tasks: roles/common/tasks/main.yml
    - name: setup KPM
      import_tasks: roles/kpm/tasks/main.yml
    - name: install Flyway
      import_tasks: roles/migrations/tasks/flyway.yml
