---
- name: ensure Kill Bill dirs exist
  become: true
  file: path={{ item }} state=directory owner={{ tomcat_owner }} group={{ tomcat_group }}
  with_items:
    - "{{ kb_config_dir }}"
    - "{{ kb_plugins_dir }}"
  tags: kpm-install

- name: generate Kill Bill files
  become: true
  template:
    src: "killbill/{{ item.name }}.j2"
    dest: "{{ kb_config_dir }}/{{ item.name }}"
    mode: u=rw,g=r,o=r
    owner: "{{ tomcat_owner }}"
    group: "{{ tomcat_group }}"
    force: no
  with_items:
    - name: killbill.properties
    - name: logback.xml
  tags: kpm-install

- name: generate Tomcat files
  become: true
  template:
    src: "{{ item.src }}/{{ item.name }}.j2"
    dest: "{{ item.dest }}/{{ item.name }}"
    mode: "{{ item.mode }}"
    owner: "{{ tomcat_owner }}"
    group: "{{ tomcat_group }}"
    force: no
  with_items:
    - src: killbill/conf
      name: setenv2.sh
      mode: u=rwx,g=rx,o=rx
      dest: "{{ catalina_base }}/bin"
  tags: tomcat

- name: run KPM install
  become: true
  killbill:
    kpm_path: "{{ kpm_path }}"
    kpm_yml: "{{ kpm_yml }}"
  tags: kpm-install
