---
- name: generate Tomcat files
  become: true
  template:
    src: "{{ item.src }}/{{ item.name }}.j2"
    dest: "{{ item.dest }}/{{ item.name }}"
    mode: "{{ item.mode }}"
    owner: "{{ tomcat_owner }}"
    group: "{{ tomcat_group }}"
  with_items:
    - src: kaui/conf
      name: setenv2.sh
      mode: u=rwx,g=rx,o=rx
      dest: "{{ catalina_base }}/bin"
  tags: tomcat

- name: run KPM install
  become: true
  killbill:
    kpm_path: "{{ kpm_path }}"
    kpm_yml: "{{ kpm_yml }}"
  tags: kpm-install

- name: Create ROOT directory to unarchive the WAR
  become: true
  file:
    path: "{{ catalina_base }}/{{ kaui_webapps }}/ROOT"
    state: directory
    mode: '0755'

- name: Expand WAR file if not already done
  become: true
  command: |
    "{{ java_home }}/bin/jar" -xf ../ROOT.war
  args:
    chdir: "{{ catalina_base }}/{{ kaui_webapps }}/ROOT"
    creates: "{{ catalina_base }}/{{ kaui_webapps }}/ROOT/WEB-INF"
  tags: kaui-logback

- name: Copy logback.xml
  become: true
  template:
    src: "kaui/{{ item.name }}.j2"
    dest: "{{ catalina_base }}/{{ kaui_webapps }}/ROOT/WEB-INF/classes/logback.xml"
    mode: u=rw,g=r,o=r
    owner: "{{ tomcat_owner }}"
    group: "{{ tomcat_group }}"
    force: true
  with_items:
    - name: logback.xml
  tags: kaui-logback

- name: Recursively change ownership for the expanded ROOT
  become: true
  file:
    path: "{{ catalina_base }}/{{ kaui_webapps }}/ROOT"
    state: directory
    recurse: yes
    owner: "{{ tomcat_owner }}"
    group: "{{ tomcat_group }}"
    mode: u=rwX,g=rX,o=rX
  tags: kaui-logback

- name: Remove root archive
  become: true
  file:
    path: "{{ catalina_base }}/{{ kaui_webapps }}/ROOT.war"
    state: absent
  tags: kaui-logback
